### ISSUE TITLE
cube depth problem

### ISSUE THREAD

**Issue by prosenkranz** [hodasemi/vulkan#14]
Huhu,

hab mir das problem nochmal angesehen.

Ich hab mit dem letzten nightly build von Renderdoc sogar einen Capture hinbekommen. Aber die scheinen noch nicht so weit zu sein, dass man durch die einzelnen eintraege im command buffer durchgehen kann.

Nach genauem hinsehen hab ich aber gemerkt, dass DepthClamp an ist:
```cpp
rasterization.depthClampEnable          = VK_TRUE;
```
... und die `near` und `far` Parameter in `CubeRenderer::CubeRenderer()` vertauscht sind:
```cpp
proj = glm::perspective(45.0f,
                            static_cast<float>(GlobalHelper::getWindowWidth())/
                                static_cast<float>(GlobalHelper::getWindowHeight()),
                            100.0f,   // <--- near
                            0.1f);     // <--- far
```

Das objekt war also eigentlich im falschen z bereich und durch das DepthClamp wurde das einfach alles in eine Ebene geclamped.

DepthClamp wuerde ich auch ausmachen, weil du sonst spaeter objekte hinter der kamera siehst ;P

**Comment by hodasemi** [comment]
DepthClamp war auch ein Punkt bei dem ich gezweifelt habe was da passiert. Ich wäre nie auf die vertauschten Parameter gekommen. 
Vielen Dank, der Würfel wird jetzt richtig dargestellt.
